### ISSUE TITLE
PHP 8.3 Support - Use of "static" in callables is deprecated

### ISSUE THREAD

**Issue by markomilivojevic** [manticoresoftware/manticoresearch-php#231]
Getting deprecation message when upgrading to PHP 8.3:

vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Index.php:144
Use of "static" in callables is deprecated

**Comment by sanikolaev** [comment]
@markomilivojevic is this reproducible in the dev version? IIRC we fixed smth like this recently.

**Comment by markomilivojevic** [comment]
Yes, it is still reproducible.

You recently changed 'self' to 'static'. But the 'static' also creates the problem.

**Comment by Nick-S-2018** [comment]
@sanikolaev  done in https://github.com/manticoresoftware/manticoresearch-php/pull/232. Pls review the fix.

**Comment by sanikolaev** [comment]
@Nick-S-2018 approved

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch-php/pull/232
